language: java

jdk:
  - oraclejdk8

notifications:
  email: false
  irc:
    channels:
    - "irc.stealth.net#Sotechat"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
    - '#%{build_number} %{message} (%{branch} : %{author}): %{commit_message}'

addons:
    firefox: "latest"
    code_climate:
        repo_token: b3947eb04b867918f437bf3b54e5a96614e3651282214fb15a81fc62c74ce47a

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - npm install karma

script:
  - karma start --single-run --browsers PhantomJS test/karma/config/unit.js
 
after_success:
  - bash <(curl -s https://codecov.io/bash)

